## Preparacion de los Datos

### 1) Cargar el dataset

In [2]:
import pandas as pd

# Cargar el archivo
df = pd.read_csv("telecomx_clean.csv")

# Verificar estructura
df.head()

,ClienteID,Churn,Genero,Adulto_Mayor,Tiene_Pareja,Tiene_Dependientes,Antiguedad_Meses,Servicio_Telefono,Lineas_Multiples,Servicio_Internet,...,Soporte_Tecnico,Streaming_TV,Streaming_Peliculas,Tipo_Contrato,Factura_Electronica,Metodo_Pago,Cargo_Mensual,Cargo_Total,Cuentas_Diarias,Cantidad_Servicios
0,0002-ORFBO,0,Female,0,1,1,9,1,No,DSL,...,Yes,Yes,No,One year,1,Mailed check,65.6,593.30,2.186667,3
1,0003-MKNFE,0,Male,0,0,0,9,1,Yes,DSL,...,No,No,Yes,Month-to-month,0,Mailed check,59.9,542.40,1.996667,1
2,0004-TLHLJ,1,Male,0,0,0,4,1,No,Fiber optic,...,No,No,No,Month-to-month,1,Electronic check,73.9,280.85,2.463333,1
3,0011-IGKFF,1,Male,1,1,0,13,1,No,Fiber optic,...,No,Yes,Yes,Month-to-month,1,Electronic check,98.0,1237.85,3.266667,4
4,0013-EXCHZ,1,Female,1,1,0,3,1,No,Fiber optic,...,Yes,Yes,No,Month-to-month,1,Mailed check,83.9,267.40,2.796667,2

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ClienteID               7043 non-null   object
 1   Churn                   7043 non-null   int64
 2   Genero                  7043 non-null   object
 3   Adulto_Mayor            7043 non-null   int64
 4   Tiene_Pareja            7043 non-null   int64
 5   Tiene_Dependientes      7043 non-null   int64
 6   Antiguedad_Meses        7043 non-null   int64
 7   Servicio_Telefono       7043 non-null   int64
 8   Lineas_Multiples        7043 non-null   object
 9   Servicio_Internet       7043 non-null   object
 10  Seguridad_Online        7043 non-null   object
 11  Backup_Online           7043 non-null   object
 12  Proteccion_Dispositivo  7043 non-null   object
 13  Soporte_Tecnico         7043 non-null   object
 14  Streaming_TV            7043 non-null   object
 15  Streaming_Peliculas     7043 non-null   object
 16  Tipo_Contrato           7043 non-null   object
 17  Factura_Electronica     7043 non-null   int64
 18  Metodo_Pago             7043 non-null   object
 19  Cargo_Mensual           7043 non-null   float64
 20  Cargo_Total             7043 non-null   float64
 21  Cuentas_Diarias         7043 non-null   float64
 22  Cantidad_Servicios      7043 non-null   int64
dtypes: float64(3), int64(8), object(12)
memory usage: 1.2+ MB

In [6]:
df.describe()

,Churn,Adulto_Mayor,Tiene_Pareja,Tiene_Dependientes,Antiguedad_Meses,Servicio_Telefono,Factura_Electronica,Cargo_Mensual,Cargo_Total,Cuentas_Diarias,Cantidad_Servicios
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,0.265370,0.162147,0.483033,0.299588,32.371149,0.903166,0.592219,64.761692,2279.734304,2.158723,2.037910
std,0.441561,0.368612,0.499748,0.458110,24.559481,0.295752,0.491457,30.090047,2266.794470,1.003002,1.847682
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.250000,0.000000,0.608333,0.000000
25%,0.000000,0.000000,0.000000,0.000000,9.000000,1.000000,0.000000,35.500000,398.550000,1.183333,0.000000
50%,0.000000,0.000000,0.000000,0.000000,29.000000,1.000000,1.000000,70.350000,1394.550000,2.345000,2.000000
75%,1.000000,0.000000,1.000000,1.000000,55.000000,1.000000,1.000000,89.850000,3786.600000,2.995000,3.000000
max,1.000000,1.000000,1.000000,1.000000,72.000000,1.000000,1.000000,118.750000,8684.800000,3.958333,6.000000

In [7]:
df["Churn"].value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

### 2) Eliminación de Columnas Irrelevantes

In [8]:
df = df.drop(columns=["ClienteID"])

# Verificamos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Churn                   7043 non-null   int64
 1   Genero                  7043 non-null   object
 2   Adulto_Mayor            7043 non-null   int64
 3   Tiene_Pareja            7043 non-null   int64
 4   Tiene_Dependientes      7043 non-null   int64
 5   Antiguedad_Meses        7043 non-null   int64
 6   Servicio_Telefono       7043 non-null   int64
 7   Lineas_Multiples        7043 non-null   object
 8   Servicio_Internet       7043 non-null   object
 9   Seguridad_Online        7043 non-null   object
 10  Backup_Online           7043 non-null   object
 11  Proteccion_Dispositivo  7043 non-null   object
 12  Soporte_Tecnico         7043 non-null   object
 13  Streaming_TV            7043 non-null   object
 14  Streaming_Peliculas     7043 non-null   object
 15  Tipo_Contrato           7043 non-null   object
 16  Factura_Electronica     7043 non-null   int64
 17  Metodo_Pago             7043 non-null   object
 18  Cargo_Mensual           7043 non-null   float64
 19  Cargo_Total             7043 non-null   float64
 20  Cuentas_Diarias         7043 non-null   float64
 21  Cantidad_Servicios      7043 non-null   int64
dtypes: float64(3), int64(8), object(11)
memory usage: 1.2+ MB

In [ ]:
df["Churn"].value_counts(normalize=True) # Proporción de clientes que abandonan

Churn
0    0.73463
1    0.26537
Name: proportion, dtype: float64

### 3) Embeddings

#### 3.1) Analisis de variables

In [10]:
pd.unique(df["Churn"])

array([0, 1])

In [11]:
pd.unique(df["Genero"])

array(['Female', 'Male'], dtype=object)

In [12]:
pd.unique(df["Adulto_Mayor"])

array([0, 1])

In [13]:
pd.unique(df["Tiene_Pareja"])

array([1, 0])

In [14]:
pd.unique(df["Tiene_Dependientes"])

array([1, 0])

In [15]:
pd.unique(df["Antiguedad_Meses"])

array([ 9,  4, 13,  3, 71, 63,  7, 65, 54, 72,  5, 56, 34,  1, 45, 50, 23,
       55, 26, 69, 37, 49, 66, 67, 20, 43, 59, 12, 27,  2, 25, 29, 14, 35,
       64, 39, 40, 11,  6, 30, 70, 57, 58, 16, 32, 33, 10, 21, 61, 15, 44,
       22, 24, 19, 47, 62, 46, 52,  8, 60, 48, 28, 41, 53, 68, 31, 36, 17,
       18, 51, 38, 42,  0])

In [16]:
pd.unique(df["Servicio_Telefono"])

array([1, 0])

In [17]:
pd.unique(df["Lineas_Multiples"])

array(['No', 'Yes', 'No phone service'], dtype=object)

In [18]:
pd.unique(df["Servicio_Internet"])

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [19]:
pd.unique(df["Seguridad_Online"])

array(['No', 'Yes', 'No internet service'], dtype=object)

In [20]:
pd.unique(df["Backup_Online"])

array(['Yes', 'No', 'No internet service'], dtype=object)

In [21]:
pd.unique(df["Proteccion_Dispositivo"])

array(['No', 'Yes', 'No internet service'], dtype=object)

In [22]:
pd.unique(df["Soporte_Tecnico"])

array(['Yes', 'No', 'No internet service'], dtype=object)

In [23]:
pd.unique(df["Streaming_TV"])

array(['Yes', 'No', 'No internet service'], dtype=object)

In [24]:
pd.unique(df["Streaming_Peliculas"])

array(['No', 'Yes', 'No internet service'], dtype=object)

In [25]:
pd.unique(df["Tipo_Contrato"])

array(['One year', 'Month-to-month', 'Two year'], dtype=object)

In [26]:
pd.unique(df["Factura_Electronica"])

array([1, 0])

In [27]:
pd.unique(df["Metodo_Pago"])

array(['Mailed check', 'Electronic check', 'Credit card (automatic)',
       'Bank transfer (automatic)'], dtype=object)

In [28]:
pd.unique(df["Cargo_Mensual"])

array([65.6 , 59.9 , 73.9 , ..., 91.75, 68.8 , 67.85], shape=(1585,))

In [29]:
pd.unique(df["Cargo_Total"])

array([ 593.3 ,  542.4 ,  280.85, ...,  742.9 , 4627.65, 3707.6 ],
      shape=(6531,))

In [30]:
pd.unique(df["Cuentas_Diarias"])

array([2.18666667, 1.99666667, 2.46333333, ..., 3.05833333, 2.29333333,
       2.26166667], shape=(1585,))

In [31]:
pd.unique(df["Cantidad_Servicios"])

array([3, 1, 4, 2, 6, 0, 5])